version: '2'
services:
  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    extra_hosts:
      - "firecloud-fiab.dsde-$ENV.broadinstitute.org:$DOCKERHOST"
      - "firecloud-orchestration-fiab.dsde-$ENV.broadinstitute.org:$DOCKERHOST"
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:515/
        tag: hub


  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    links:
      - hub
    ports:
      - 5555
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      # Workaround for chrome nodes stalling: https://github.com/SeleniumHQ/docker-selenium/issues/87
      DBUS_SESSION_BUS_ADDRESS: /dev/null
    extra_hosts:
      - "firecloud-fiab.dsde-$ENV.broadinstitute.org:$DOCKERHOST"
      - "firecloud-orchestration-fiab.dsde-$ENV.broadinstitute.org:$DOCKERHOST"
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:515/

  logs:
    image: bobrik/syslog-ng
    volumes:
      - $WORKING_DIR/logs:/var/log/syslog-ng:rw
    ports:
      - "515:514/udp"